server:
  port: 8080

spring:
  application:
    name: inventory

  jpa:
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: validate

  datasource:
    url: "jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DB:inventory}"
    username: ${DB_USERNAME:inventory}
    password: ${DB_PASSWORD:inventory}
    driverClassName: org.mariadb.jdbc.Driver
    initialization-mode: always

  flyway:
    enabled: true
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
